### ISSUE TITLE
Unable to abort http upload

### ISSUE THREAD

**Issue by edgesoft** [cerebral/cerebral#1189]
When uploading a file http.abort does not abort the upload

**Comment by christianalfoni** [comment]
This is because `uploadFile` is not using an `AbortablePromise`. Check here:

https://github.com/cerebral/cerebral/blob/next/packages/node_modules/%40cerebral/http/src/index.js#L112

To fix this you would have to refactor `fileUpload` to work with the `requestService` as you can see used with for example `delete`: https://github.com/cerebral/cerebral/blob/next/packages/node_modules/%40cerebral/http/src/index.js#L93

**Comment by christianalfoni** [comment]
Housekeeping!
