### ISSUE TITLE
FEATURE: Observables

### ISSUE THREAD

**Issue by christianalfoni** [cerebral/cerebral#129]
It is suggested that Cerebral should be able to subscribe to observables.

Inside a component:
```js
this.props.signals.todosUpdated.subscribeTo(observable);
```

Now, observables can be many things and we need to throw some examples at this. Everything from mouse events to firebase updates. Please provide examples of how you would try to use the syntax suggested to handle different kinds of observables and then we will decide :-)

**Comment by dchambers** [comment]
Hi @christianalfoni, I've been struggling to fully get it, and may have misunderstood your thinking here. In the mouse event example you mention, would this involve a subscription like this?:

~~~es6
this.props.signals.mouseMoved.subscribeTo(observable);
~~~

and are you then thinking that `observable` would look something like this?:

~~~es6
let observable = createObservable(function(observer) {
  const eventListener = (event) => observer(event); // so simple we could just use observer directly
  document.body.addEventListener('mousemove', eventListener, false);
  observer.onDispose(() => document.body.removeEventListener('mousemove', eventListener, false));
};
~~~

where a subscription could be created by Cerebral in the `mouseMoved.subscribeTo` method like this?:

~~~es6
let subscription = observable.subscribe(function(input) {
  // emit a new mouseMoved signal
});
~~~

and maybe disposed like this?:

~~~es6
subscription.dispose();
~~~

perhaps using a `mouseMoved.unsubscribeFrom` method?

**Comment by christianalfoni** [comment]
Hi again,

Yes, thanks for elaborating the idea. This is what I currently have in my mind, though all theoretical now :-)

I do not think Cerebral should be in charge of handling side effects over time "inside itself". Rather like this example give a wrapper to bind a signal to an observable subscription. Like we do with routing basically :-)

So yes, sometimes the observable will just stop itself, but exposing an `unsubscribeFrom` is not a bad idea, like:

```js
componentDidMount() {
  this.firebaseSubscription = createFireBaseSubscription();
  this.props.signals.todosUpdated.subscribeTo(this.firebaseSubscription);
},
componentWillUnmount() {
  this.props.signals.todosUpdated.unsubscribeFrom(this.firebaseSubscription);  
}
```

So yeah, I like the idea of using the components as hooks for handling these kinds of side-effects, because they know themselves better than anything else when they need them. But observables can be so many things, so just running with that for now... until we get more examples :-)

**Comment by bfitch** [comment]
Greetings from Bratislava! 

Can we treat firebase as a service and trigger a signal to start and stop a subscription rather than manage it in the component?

Should be like Ajax or web sockets right? Or am I missing a distinction?

**Comment by trueadm** [comment]
In theory, some form of decorator sugar magic could handle cases where you subscribe/unsubscribe strictly on the component lifecycle.

```javascript
import { signalObservables } from 'cerebral';
import { adapter } from 'cerebral-firebase';

@signalObservables([
	todosUpdated: adapter(new Firebase('https://example.firebase.io/todos'))
])
class Todos extends React.Component {
	render() {
		...
	}
}
```

When the component `componentDidMount` gets called, the subscription is made for you as does the unsubscription when `componentWillUnmount` gets called.

**Comment by dchambers** [comment]
> So yeah, I like the idea of using the components as hooks for handling these kinds of side-effects, because they know themselves better than anything else when they need them. But observables can be so many things, so just running with that for now... until we get more examples :-)

This is a great point @christianalfoni. The example code I shared where I had a `Subscribe` / `Unsubscribe` button was handy because it allowed me a way to pause the app before time-travel was attempted, but was completely unrealistic in that most all (all?) subscriptions will normally be created and torn-down based on component life-cycle.

> In theory, some form of decorator sugar magic could handle cases where you subscribe/unsubscribe strictly on the component lifecycle.

Yes, @trueadm, makes lots of sense that this could be sugared.

> Can we treat firebase as a service and trigger a signal to start and stop a subscription rather than manage it in the component?

@bfitch, this was the approach I originally took, but it actually creates more complexity since the app must 'manage' subscriptions that could otherwise be left to React to manage, and since in my demo it required me to provide a unique identifier so that I could identify the number of instances attempting to share the same subscription.

In [`StreamingApp`](https://github.com/dchambers/cerebral-streaming-spike/blob/master/src/components/StreamingApp.jsx) I have this code:

~~~jsx
<Ticker instrument="acme" instance="primary"/>
<Ticker instrument="acme" instance="secondary"/>
<Ticker instrument="xeta" instance="primary"/>
<Ticker instrument="xeta" instance="secondary"/>
~~~

where the `instance` prop is a unique identifier I shouldn't really need! OTOH, @christianalfoni's approach doesn't have this problem.

**Comment by dchambers** [comment]
There's another nice property of this solution I just thought of. Whereas server-sent events would normally make time travel more difficult &mdash; the developer must have a way of disabling all events temporarily, and must remember to do that before pressing the back button &mdash; having the concept of _observables_ baked into Cerebral makes it possible for Cerebral to buffer any updates as soon as the developer goes back in time, **and** until the developer comes back to the present.

**Comment by dchambers** [comment]
> So yeah, I like the idea of using the components as hooks for handling these kinds of side-effects, because they know themselves better than anything else when they need them. But observables can be so many things, so just running with that for now... until we get more examples :-)

So the remaining question is: "Are there any use-cases that can't be catered for using the observable pattern?" My hunch is that there won't be, but probably one to sleep on...

**Comment by christianalfoni** [comment]
Ah, yes, time travel is also something to take into account here. Anything related to "time moving" is a big challenge with time travel debugging. Like setTimeout, setInterval or any observable.

The big problem is that an observable as a firebase subscription would make sense to buffer or freeze, but an observable representing mouse clicks does not make sense to buffer or freeze.

So if we just let the subscriptions run, which makes sense for mouse clicks observable, you can fire new signals after going back in time, rewriting history... which you really should be able to.

But in the case of firebase, you would risk rewriting history unintentionally.

Then we could like define categories of observables, but that is just silly as it is only to make time travel debugging work as expected. This is a difficult one.

Maybe we should remove the ability to rewrite history automatically and just have a button saying "rewrite history". So if you move back to signal 3/10 you look at a snapshot of your application. Any signals will just be ignored, it being an observable or any other signal. If you move back to 10/10 signals will be handled again, or if you click "rewrite history", bringing you to 3/3.

I do not think buffering would work as expected, though I see the point. The reason just being that an observable could just as well be mouse events.

Okay, this definitely needs more thought :-)

**Comment by dchambers** [comment]
> The big problem is that an observable as a firebase subscription would make sense to buffer or freeze, but an observable representing mouse clicks does not make sense to buffer or freeze.

I actually thought about that and was going to mention it, but I'm not sure it's a huge problem. At the point I go back in time then I don't want my mouse events to be processed. More to the point, I probably don't even want the mouse events to even be buffered, but I can easily avoid that by not hovering over the window if there is some visual indication in the Cerebral debugger of new events being generated as I move my mouse &mdash; even while I'm back in time.

> So if we just let the subscriptions run, which makes sense for mouse clicks observable, you can fire new signals after going back in time, rewriting history... which you really should be able to.

Only the end-developer can say when this might be okay to do, so they should have control over it. They could click a button to release buffered events for example. If the events include server events then bad things may happen since the client state may be out of sync with the server state, but again the developer is taking the responsibility for this.

> Maybe we should remove the ability to rewrite history automatically and just have a button saying "rewrite history". So if you move back to signal 3/10 you look at a snapshot of your application. Any signals will just be ignored, it being an observable or any other signal. If you move back to 10/10 signals will be handled again, or if you click "rewrite history", bringing you to 3/3.

Again, the entirely safe thing to do is not to allow buffered signals to be played until the developer gets back to the current time. For things like mouse events the developer might want a way to override that, but as long as it's their choice and there is a warning indicator, then I think that's okay.

> Okay, this definitely needs more thought :-)

Yep, good to thrash the ideas though :-)

**Comment by dchambers** [comment]
Another option of course is to delineate state dependent events. In this case, state-dependent events would always be buffered, while mouse events would always be sent. The problem here though is that those continued mouse events will make time travel impossible since they will force time forward all the time.

**Comment by christianalfoni** [comment]
Yeah, exactly. Hm. I do like the idea of just buffering up events and letting the developer choose to like run them... though. Lets say you go back in time and you want to remove an item from a list. That click should not be a buffered event because that item in the list might not exist in the future :-) But an event from firebase should always be buffered because it really is a future event.... haha, mind bending.

So we really do have two categories of observables here. One type of observable that can be handled at any time (like a click), which could rewrite history. And an other type of observable that can never rewrite history because it is "real time", like firebase.

One suggestion to solve this, which I do not like, is to actually have two types of subscriptions. One where Cerebral buffers and one where it does not. Its kinda mind bending to know which one to use.

I think it might be good to take this in several steps. Like the first implementation could be:

1. Going back in time will ignore all signals fired. You have to be "in the present" or click "rewrite history" to actually bring your application into the future

2. Implement subscribing to observables without buffering, they will also be ignored as the rest

We put an "experimental" sticker on it and try it out. It is the minimal implementation for most value I think. When we get our hands on it and feel that something is "off" in regards of buffering etc. we at least have an implementation that is working and can be tested further. It is hard to make all the decisions now I think :)

**Comment by trueadm** [comment]
@christianalfoni I definitely think observables are something that should be on your 1.0 milestone. They're essential to any form of real-time app that depends on this stuff.

Also maybe it's easier to simply buffer everything. Why? Because it's possible that something other than the user triggers a "click" event. There really is no real way to differentiate the source of the input that has triggered the event.

You could break things into separate timelines that break at a certain point (isn't that how parallel universes work anyway? :P).

**Comment by dchambers** [comment]
> That click should not be a buffered event because that item in the list might not exist in the future :-) But an event from firebase should always be buffered because it really is a future event.... haha, mind bending.

Oooh, good point! It's a slightly bad example since a mouse click wouldn't likely be implemented as an observer, but that's actually just luck since it could just as easily be mouse movement (e.g. drag & drop) that will incorrectly be applied to a future history even though it's being generated based on a past event.

In fact, the drag & drop example is particularly pernicious since the click event would likely not be an observable, whereas the subsequent drag would be. So we'd have some of the events being applied immediately while other are buffered for replay against a time they they're not relevant for!

**Comment by dchambers** [comment]
> Also maybe it's easier to simply buffer everything. Why? Because it's possible that something other than the user triggers a "click" event. There really is no real way to differentiate the source of the input that has triggered the event.

@trueadm, we're explicitly saying that it's not always safe to buffer everything. Mouse events only make sense based on the view in the current time frame, whereas stateful server events can only safely be processed when you're back to the point in time when they were buffered.

It's probably safest to buffer stateful events until you return to the point in time where they were generated, and permanently discard mouse events (non-stateful events?) while time travelling since they are always detrimental to time travelling, and can easilly be re-generated by the user once he stops time travelling anyway.

**Comment by dchambers** [comment]
> So we really do have two categories of observables here. One type of observable that can be handled at any time (like a click), which could rewrite history. And an other type of observable that can never rewrite history because it is "real time", like firebase.

@christianalfoni, In case my previous thought splurge isn't as readable as I'd hoped, I've also come to the conclusion that there are two observable types:

  * One where events are buffered while we're time travelling.
  * But where the other type of events are permanently discarded while time travelling.

**Comment by trueadm** [comment]
@dchambers mouse events, click events, any form of events can be destructive. Imagine you had a window resize event, that triggered a set of actions upon being fired. Simply by opening the dev tools in Chrome, I'd have that event fire and it would re-write my history.

I propose something different. The user, via the dev tools, has the option of "pausing" time. In which case, all signals get buffered that come in via subscriptions. Then this allows them to play through time and go back as much as they'd like. If they choose to re-write time, they'll need to "un-pause" time or something of that effect at a given point.

**Comment by dchambers** [comment]
> I propose something different. The user, via the dev tools, has the option of "pausing" time. In which case, all signals get buffered that come in via subscriptions. Then this allows them to play through time and go back as much as they'd like. If they choose to re-write time, they'll need to "un-pause" time or something of that effect at a given point.

@trueadm, this is good in that it's becomes a very deliberate action by the user. And, as you point out, even mouse events (that pre-date observables) can otherwise unintentionally cause time to be re-written even though this might lead to the client being out of sync with the server.

On the other hand, allowing the user to un-pause time at a previous point is dangerous since the client might then be out of sync with the server, even pre-observables. Additionally, with observables, we definitely know that any buffered events are no longer relevant.

It would seem safer that the un-pause button requested the user to return back to present time, or face potential inconsistencies. And, even if they did agree to go forward to current time, we'd still need to discard any client-side generated observable events we'd received since those would no longer necessarily be relevant in the original time frame.

**Comment by trueadm** [comment]
@dchambers I agree completely there. Although an experimental feature might be to allow "rewriting time" from a previous state in history – although the norm should be to simply resume at present. I mean, why would someone even try and rewrite time? It's a nice gimmick, for sure, but what applicability has that got in the real world?

**Comment by dchambers** [comment]
> I mean, why would someone even try and rewrite time? It's a nice gimmick, for sure, but what applicability has that got in the real world?

Right, so that's the point I was also trying to make to you; that's it's just safer to not do it. Even so though, you still need to classify the two types of observable event so that you don't buffer any events that are being generated via the UI for the current time frame when while time travelling. Only events for the original time-frame (typically server generated) are safe to buffer.

I think we now all get it, and I think it will probably all just work out nicely, but a 'Beta' label might make sense anyway.

**Comment by trueadm** [comment]
Thinking about this more, the subscription needs to be made from a signal.

Why? Well if you undo time from X10, back to event X4 and then you proceed to X5, causing a component to mount, and that mount fires off a new subscription: that subscription might have unnecessary side effects that we do not want. 

Ideally, if all subscriptions are made from within signals, then we could make it so signals that fire subscriptions are silently ignored when in time travel mode.

**Comment by trueadm** [comment]
Maybe a way of doing it as by adding a type called `streams`? The code could work like this:

```javascript
import controller from 'cerebral';

const firebaseStream = {
    subscribe(input, state, output, services, subscription) {
        const firebase = new Firebase(input.url);

        services.firebase.on("value", snapshot => {
            output(snapshow.val());
        });

        subscription.firebase = firebase;
    },
    unsubscribe(input, state, output, services, subscription) {
        subscription.fireabse.off();
    }
}

const todoStream = [
    updateTodos
];

controller.stream('firebaseStream', firebaseStream);

class Todos extends React.Component {
    componentWillMount() {
        const firebaseStream = this.props.streams.firebaseStream;
        //the subscription will pass its subscription data to the processSignal
        firebaseStream.subscribe({url: "https://someurl.firebaseio.com/todos"}, todoStream);
    }
}
```

**Comment by christianalfoni** [comment]
Hm, yeah, that is a good point. Though if we ignored all signals when moving back in time this would not be a problem. You know... I am going to watch Back To The Future tonight, will have an answer tomorrow ;-)

No, but seriously, if we think about this. If you move back in time and change something you create a new future, a forked future. But that is not what we want with time travel debugging. What we want is a snapshot of the past, to debug it. That means we should not allow any changes when moving back in time... meaning ignore all signals and subscriptions.

We can allow to fork the future, but I think the developer has to explicitly ask for that, throwing away the current future.

So by default, moving back in time means that all signals will be ignored. You can not do anything in your app. Any current running subscriptions firing off signals will be ignored and any new subscriptions will be ignored. When moving back to the future signals will start to run again.

The problem is that a future observable might have had some events while you were stuck in the past, but I think we should look at this as a limitation. This is about debugging your app. If three new todos arrived on your subscription while you debugged in the past it is not a problem that those got ignored. It is a good limitation to make everything else work I think :-)

So stepping back in time basically means:

1. "Do not allow my app to be affected by time in any way"
2. You can now look at snapshots in the past, but not do any changes
3. Moving back to present means "Let my app be affected by time again"

Anything happened in time between you were stuck in the past and moving back to the future is "lost". The only way to solve this, as I see it, is to create a fork of your app when you actually move back in time allowing your future app "master" to still be updated. But this requires to instances of the app running and is just way too complex I think :-)

**Comment by trueadm** [comment]
@christianalfoni I agree there, all signals and "streams" should be ignored if in the past. Currently, using Cerebral with subscriptions is a nightmare to debug, so would be awesome to come up with a final strategy. I don't mind adding my "stream" concept as I feel it compliments the signals/computed quite well. What do you think about that?

**Comment by christianalfoni** [comment]
Hm hm, yeah, that is the last question. I think it would be wise if we fix the debugger first. The way we can test this without implementing any new apis. So with the new debugger you would just wire up firebase in a component and fire off a signal on each update:

```js
        const firebase = new Firebase(input.url);

        services.firebase.on("value", snapshot => {
            this.props.signals.newFBValueReceived(snapshot.val());
        });
```

Just to verify that it works to move back in time. Then we could take the next step and implement an API. And I think it would be wise to create an API that just makes Cerebral observe observables, not put them inside Cerebral. As I see it is really no reason for the Firebase subscription to be inside Cerebral. It should rather be converted to an observable exposed to the components that are interested in using them, using RxJS, Babel etc:

```js
import {firebase
this.props.signals.todosUpdated.subscribeTo(Observable.from(new Firebase(url)));
}
```

check out: https://docs.google.com/file/d/1uEVcOgJIMsHjN1vypKKyfmDRg_bz5cKXpo0v4Nc0q8NfqKolBeSDHIj8z9GS8A4EiMpZ8QQ3l87Q_wF3/edit

That way it is the same API to handle any other observable and the only thing Cerebral does is to fire a signal on each event of the observable.... which will just be ignored when moved back in time.

I am no expert on observable, but I have a feeling we should make it work beautifully with the soon Native observable about to arrive :-)

**Comment by dchambers** [comment]
> check out: https://docs.google.com/file/d/1uEVcOgJIMsHjN1vypKKyfmDRg_bz5cKXpo0v4Nc0q8NfqKolBeSDHIj8z9GS8A4EiMpZ8QQ3l87Q_wF3/edit

Thanks for the link. I hadn't realized that async generators had been dropped for observables!

**Comment by trueadm** [comment]
@christianalfoni the new ES2016 spec for Observables looks good. Although it might not get through, an alternative might be to implement RxJs's Observable: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md

**Comment by garth** [comment]
Interesting discussion, time traveling aside, I would not be in favour of exposing observables other than immutable controller state to the UI components.

If you need to track mouse events, that can probably be done within the UI without involving cerebral.

But if you need to receive server events then services would be a better solution. A service is responsible for managing external observables and converting events into cerebral signals. This way UI components can continue to be stateless and we can keep the benefits of the immutable store.

Ideally services should be a core feature of cerebral and be able to observe state in the same way as UI components do as well as subscribing to externals events.

**Comment by christianalfoni** [comment]
I really like what you state here: "This way UI components can continue to be stateless and we can keep the benefits of the immutable store." and "Ideally services should be a core feature of cerebral and be able to observe state in the same way as UI components do as well as subscribing to externals events."

I think that just nails it :-)

To support this I suppose we have to create a signature for services. Just a custom implementation with firebase. This could actually be a generic `cerebral-firebase-service`:

```js
import Controller from 'cerebral';
import Model from 'cerebral-baobab';
import FireBase from 'firebase';

function FirebaseService(controller) {
  const connections = {};
  return {
    start(url, path, signal) {
      const connection = connections[url] = {
        dataRef: new Firebase(url),
        listener(snapshot) { controller.signals[signal]({value: snapshot.val()}) }
      };
      connection.dataRef.on('value', connection.listener);
    },
    stop(url) {
      const connection = connections[url];
      connection.dataRef.off('value', connection.listener);
    }
  }
}

const model = Model({
  todos: []
});

export default Controller(model, {FireBase});
```

That said, I still think we should allow signals to have a "props.signals.someSignal.subscribeTo(someObservable)". 

Does this make sense? :-)

**Comment by garth** [comment]
@christianalfoni, Services also fit into the cerebral-modules stuff that I've been working on with @guria. Each service has an init function that takes the controller as a parameter.

**Comment by bfitch** [comment]
@garth @christianalfoni I've also landed on a cerebral-falcor-service for the falcor integration. It will take a baobab model, instantiate falcor and sync them, exporting get, set, call actions for updates.

I'd love to try it with the modules stuff.

**Comment by garth** [comment]
@bfitch after a bit of testing I can publish a pouchdb service on npm. I guess it would be similar.

**Comment by Guria** [comment]
Seems modules covered most of needs. Closing now
