### ISSUE TITLE
What happened to mobx-state-tree

### ISSUE THREAD

**Issue by darkowic** [cerebral/cerebral#1399]
There was mobx-state-tree plugin for cereblar for version 4 (codesandbox source code is using it) but it is no longer visible in the repository. Is it abandon and removed?

**Comment by christianalfoni** [comment]
Hi there @darkowic !

Yeah, we wanted Cerebral 5 to be simple and straight forward. With different state models etc. it became a maintenance issue and the library felt a bit "all over the place" :)

If you like mobx-state-tree you can check out https://overmindjs.org which is the successor to Cerebral, which uses similar approach to mobx in terms of managing changes and tracking of state :)

**Comment by darkowic** [comment]
Oh wow so, another library? Does the overmind use mobx under the hood? I
was hoping to use cerebral with mobx in my project (because it is already
preety mature) but it seems like creating again something new... I am
affraid

czw., 25 kwi 2019, 21:47 użytkownik Christian Alfoni <
notifications@github.com> napisał:

**Comment by darkowic** [comment]
@christianalfoni the last question - is it possible to still use mobx state tree together with cerebral 5? What has to be done to make it possible?

**Comment by christianalfoni** [comment]
Hehe, completely understand you are afraid, things move really fast in JavaScript. The reason we chose to create a new library is a big lesson learned in Cerebal. "Do not reimagine the API of a project". The reason is that current users needs to refactor a lot and you also have to keep docs around for the previous version. It has been painful for developers to keep up with Cerebral which I am really sorry for.

Cerebral 5 does not have a model replacement approach like Cerebral 4. The reason is that every time there was a new "model solution" we had to maintain documentation and do some sort of change to make it work. Codesandbox today is running on Cerebral with Mobx-State-Tree actually, but it is currently being refactored to Overmind, which was just officially released as production ready.

So you should definitely not feel afraid when Codesandbox is about to use it :) Mobx-state-tree is a solid project, though a bit verbose and I would argue the devtools of Cerebral and Overmind gives more insight. 

So yeah, sorry about not allowing this combination anymore, but it was necessary lock down a maintainable API of Cerebral moving forward :-)
