### ISSUE TITLE
reaction errors

### ISSUE THREAD

**Issue by Makvagabo** [cerebral/cerebral#1404]
1. types for reaction is wrong. function of creating subscribe returned object Reaction, but now - void.
2. Reaction don't automatically destroyed after component unmount in reactjs.

Thank you.

**Comment by christianalfoni** [comment]
Hi there and thanks for reporting this!

I just came off vacation and will have a look at this ASAP :)

**Comment by christianalfoni** [comment]
Hi there!

Thanks for reporting. This is now fixed in next release :)

I did not change the type, as it was actually a bug that the object was returned. I did not remove the returned object though afraid of breaking existing apps. 

That said, the reaction is now cleaned up correctly :)

**Comment by michaek** [comment]
Sorry to comment on a closed issue, but I'm not sure (2) on this issue is actually addressed. I see that the call to `.destroy()` on created reactions has been added to the view unmount, but it seems from my testing that destroy doesn't have the desired effect - the reaction callback still executes when the store value changes, even when the reaction's component is unmounted.

I've hacked an ugly example of this into the Todo demo app: https://codesandbox.io/s/cerebral-todomvc-1dwcr?file=/src/components/TodoApp.jsx . We have a reaction in a nested component that will log whenever todos change, and that nested component will unmount whenever we edit a todo (just a way to test the unmount behavior). As we create and edit more todos, the logging callbacks from the watch on `todos` keep growing - they're not auto-removed by connect's view, or manually removed by calling destroy on the reaction.

I haven't yet dug into the cerebral watch code to come up with an explanation, but I wanted to raise this to see if there was something simple I'm missing, or if there is a problem you've got a hunch on how to solve it. Thanks!

**Comment by michaek** [comment]
It looks like `this.dependencyMap` is always null for the reaction. If I manually invoke `registerDependencies` on the reaction, it is cleaned up when I invoke `.destroy`, but not automatically when the component unmounts. It's not clear to me exactly where the missing pieces are (part of it might be invoking createDependencyMap instead of registerDependencies in Reaction.initialize?), but it looks like I can work around this issue by invoking registerDependencies/destroy in my component lifecycle.

**Comment by michaek** [comment]
A last (I hope) wrinkle to this is that when invoking destroy manually, I'm seeing `this.debuggerWatchMap[depsKey]` as undefined in Devtools.updateWatchMap (throwing an error), suggesting that there's still a gap in the structures that are expected to be created.

**Comment by michaek** [comment]
@christianalfoni I think it's reasonable to reopen this issue (for reported case 2), but should I recap my observations on a new issue instead?

**Comment by michaek** [comment]
This was resolved by https://github.com/cerebral/cerebral/commit/b08788d6ef1c9bfde0c8127838875651371bcd5a
