### ISSUE TITLE
function-tree Can't resolve './StopExecution'

### ISSUE THREAD

**Issue by caltn** [cerebral/cerebral#1419]
v3-v5    Can't resolve './StopExecution',  Content.js, Path.js
But v2 has.
it is wrong?
![aa](https://user-images.githubusercontent.com/7614929/66254530-0a03f980-e7aa-11e9-98ba-b7ff5fd74697.png)

**Comment by christianalfoni** [comment]
Hi there @caltn!

You have a bit more info on how this issue occurs? If you are upgrading you have to make sure that the packages match. It can be a good idea to remove any reference in your `package.json` to `function-tree`. This is just to make sure that when you install Cerebral it uses its correct dependent version of function-tree. If you are using function-tree explicitly in your code, just make sure you install the latest of all of the packages.

```
npm install function-tree@latest cerebral@latest @cerebral/react@latest
```

Hope this helps, or please give some more details on your package.json setup so that we can figure it out :)

**Comment by henri-hulski** [comment]
@christianalfoni what do you think about the fix from @fmal?

**Comment by caltn** [comment]
hi @christianalfoni , I just install cerebral@3.6.0,  cerebral/react@3.2.2.   `function-tree` is dependence of cerebral.  The commit of  @fmal is right, need remove  unused code
