### ISSUE TITLE
Cerebral 5.2.0: inferno does render child before parent 

### ISSUE THREAD

**Issue by bernhardreisenberger** [cerebral/cerebral#1426]
hi.

With the latest release 5.2.0 of Cerebral there is an issue with Inferno.

It may happen, that the child component will be rendered before the parent component. This is bad, if the parent defines the visibility of the child components.

In my application, i have one modal (parent component). only this modal component is used on the whole website. to display different content, i use child components, and switch them as needed. for simplicity, i check the visibility of the modal in the parent component.
I tried my best by providing a simplified example, visualizing the problem.
https://codesandbox.io/s/parent-child-bug-jhcdz

In version 5.1.1 it worked fine this way, but with 5.2.0 it will randomly break.
The problem does not occur with react, so i guess it is caused somewhere in the view package

**Comment by christianalfoni** [comment]
Okay, I found a bug in Cerebral itself here. This was such an amazing example to detect it, so thank you immensely for taking the time to do that! 👍 😍 

This bug would actually cause this issue to potentially happen in any view layer. Unlikely, but basically impossible to detect. 

The reason it happened at "16" is because the ID of the "watchers" became `["watch_1", "watch_2", "watch_10"]`. The sorting to put these in the right order was not good enough. It made it `["watch_1", "watch_10", "watch_2"]` instead of `["watch_1", "watch_2", "watch_10"]`... which is why the child rendered before the parent 😄 

If you want to test it, install `npm install cerebral@next @cerebral/inferno@next`

**Comment by bernhardreisenberger** [comment]
nice to read. thank you very much for fixing this.

already tested it, and it is working.
