### ISSUE TITLE
modules: provide emit method

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#178]
namespaced `module.emit(event)` could be useful to communicate between modules or just inform that something happened.

**Comment by abalmos** [comment]
My gut reaction is I would prefer Cerebral not go this route. One of Cerebral's main advantages is that it reduces the mental load needed to reason about an application. Adding arbitrary side communication would hurt that advantage and including event emitters in the module API would effectively be endorsing it usage. That said, maybe we should work through some examples :) What are some use cases?

Side thought: I think one can achieve this result without changing Cerebral. A module could expose an EventEmitter through meta.

**Comment by Guria** [comment]
@abalmos events already exists. controller is event emitter. My suggestion is only to provide the same namespacing support here too.

**Comment by christianalfoni** [comment]
Since I think it is important that we keep this event emitting as an internal tool, not that many events and that we can just do `controller.emit('myNameSpace.someEvent')`, I do not see any reason to bring in namespacing to it?

At least not for now.

Please reopen if you want to continue discussion. Just cleaning up issues :)
