### ISSUE TITLE
Error when use "defaultInput" and "input" together

### ISSUE THREAD

**Issue by pltnkv** [cerebral/cerebral#196]
```
function someAction (input) {
  console.log(input) //i expect input == {defaultParam: 'defaultValue', customParam:'str'}
}

someAction.defaultInput = {
	defaultParam: 'defaultValue'
}
someAction.input = {
	customParam: String
}


//.........
cerebral.signals({'tested': [someAction]});


//.........
signals.tested({customParam: 'str'});

```

This code throws next error:

> Uncaught Error: Cerebral: You are giving the wrong input to the action "someAction" in signal "tested". Check the following prop: "customParam"

**Comment by christianalfoni** [comment]
Noted, will make a fix for this, thanks!

**Comment by saulshanabrook** [comment]
We are considering removing type checking from cerebral core: https://github.com/cerebral/cerebral/issues/260 If you have any use cases for keeping this in node, could you open those in the other issue? I am closing this for now, to help clean up old issues, and since this feature is likely to be removed.
