### ISSUE TITLE
getting this.props.signals[Module][Signal].sync is not defined

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#246]
Sorry for the noob question. I tried to follow the example on http://www.cerebraljs.com/signals under the section *Force synchronous UI updates*, but have been getting the error `_this2.props.signals.example.changeInput.sync is not a function`

Here is my gist: https://gist.github.com/awei01/69ecf9b722eeec825125438755ff932d

Also, can someone explain a use case where this would be necessary? Any insight is appreciated.

**Comment by Guria** [comment]
Outdated doc. Use `signal(payload, { immediate: true })`

**Comment by awei01** [comment]
Thanks for the fast response. Can you give me a use case where this might be necessary?

**Comment by maxfrigge** [comment]
Try using this (as stated by @Guria)

```
<input 
  type="text" value={ this.props.display }
  onChange={ (e) => { this.props.signals.example.changeInput({ value: e.target.value }, { immediate: true }) } }
/>
```

This is necessary on input fields, because without it cerebral collects updates with [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) to collect state changes for better performance. It's only a very short delay but it causes unexpected behaviour on user input fields. Try using it with `{ immediate: false }` and then set the cursor in the middle of the input text and delete or type a character .. you will notice that the cursor jumps.

**Comment by awei01** [comment]
Thanks guys. Much appreciated.
