### ISSUE TITLE
triggering signals from within other actions

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#255]
Hi, I've been getting my feet wet with cerebral and it's been a great experience so far. 

I'm wondering why triggering signals from within other actions is such a bad idea. There are some cases where I think it might be unavoidable, e.g. `cerebral-module-firebase`. 

Any insight is appreciated.

**Comment by christianalfoni** [comment]
Good question @awei01 and we have been discussing this a lot :-)

The thing is that you can trigger signals from within other signals now, but you do it with "composing" instead of a magical linking mechanism.

```js
import someAction from '../actions/someAction';
import signalB from './signalB';
[
  someAction,
  ...signalB
]
``` 

The reason it was initially brought up is that in old version of Cerebral you might want to run `signalB` in the context of the module of where it was defined. This was related to when Cerebral had the "module" by default on the context. This might not make much sense, but that was partly the reason it was removed. It creates an extra complexity and isolates the modules, something I wanted to avoid... at least by default.

So composability is one of the really great features of the signals that I wanted to keep "pure". It just makes the code better because you explicitly set its dependencies as you import them at the top of the file instead of some string the magically points to some other piece of code :) Does that make sense?

**Comment by awei01** [comment]
Hi, sorry if my initial issue was unclear. I understand the idea of composing signals and this makes sense for certain cases. But, how about the case of listening for a change in state somewhere. For example, in `cerebral-module-firebase` you can listen for `childAdded` which would then trigger a new signal altogether. It is not a simple `Promise.resolve` situation because the `childAdded` callback can be fired many times and thus, I believe, needs to trigger a completely new signal. Here's a simplified example:

```
function startTimerAction() {
   setTimeout(() => {
       // somehow trigger the signal
       controller.getSignals('timerUpdated', { some data });
   }, 1000);
}

function startTimerActionNotSureIfThisWillWork({ output }) => {
    setTimeout(() => {
        output.updated({ timer data });
    }, 1000);
}
```

I believe that after the first iteration of `startTimerActionNotSureIfThisWillWork`, the signal chain will be complete and `output.updated` won't work anymore. 

Hopefully that clarifies my use case...

**Comment by NervosaX** [comment]
Personally when I'm listening for state, I do it in the view layer. Feels a little odd to me too, considering the rest of my business logic is in cerebral. However, it does work well. It also means you have have long running signals listening for changes...

```
componentDidMount() {
  const myThing = new MyThing();
  myThing.on("foo", () => {
    this.props.signals.foo();
  });

  myThing.on("bar", () => {
    this.props.signals.bar();
  });
}
```

Is this the sort of thing you meant, @awei01 ?

**Comment by awei01** [comment]
@NervosaX Thanks for the response. This pattern could work, however, I feel it couples these external services into the view components, which I don't think is ideal. It makes testing the component/service as separate entities a little harder. 

Anyway, I ended up solving the issue by just triggering another signal. I appreciate your input though.
