### ISSUE TITLE
Waiting an user interaction between actions

### ISSUE THREAD

**Issue by gustavorino** [cerebral/cerebral#298]
Hi Guys, first of all, awesome work!! :+1: 

I'm building a form with a reset button. When the user clicks the button a confirm modal pops up with two options: Confirm or Cancel.

Is it possible to expose the output callbacks to the View/React and solve this flow with a single Signal ?

```
// it would look like this : 
export default [
  showResetModal, {
    confirm : [  // called by Confirm Button Click 
       resetForm, 
       closeResetModal
    ],
    cancel : [  // called by Cancel Button Click 
       closeResetModal
    ]
  }
]
```

Thanks!!

**Comment by Guria** [comment]
We duscussed such pattern in diacord recently. I'll try to dig it from history and but it here.
Short answer, no. You shouldn't expose output callbacks to view layer. You still need separate signals for buttons, but you can use action factories to help your signal know when it should proceed to output. 
I am on mobile now. Will try to post detailed example tommorow.

**Comment by christianalfoni** [comment]
Hi @gustavorino As @Guria says this was not intended initially when defining scope of signals. That said, it is technically possible. The reason it is a bit "off" is because you would set this signal into "pending state" and a side effect not defined in this flow would cause the `showResetModal` to resolve. Typically such a side effect is a HTTP request, but in this case it could be like a "view service". The thing is that also the debugger would look at this as a "pending signal", making it rather unclear how signals run. You would indeed see the signal pending and be resolved, but you would not know WHY it was resolved... it just suddenly went down the confirm/cancel path.

So for clarity I think:

```js
// Open
[
  set('state:app.showModal', true)
]

// Confirm
[
  set('state:app.showModal', false),
  resetForm
]

// Close
[
  set('state:app.showModal', true)
]
```

It is just more clear, the debugger will show you everything that is happening and the view stays dumb (no special hook into running signals). Also the composability is lost. You would not be able to compose in the "opening" or "closing" of the modal to other chains.

It is a cool idea indeed, but I do not think you get more value structuring it that way :-) But please, continue the discussion and I am sure @Guria comes up with something you can test your hypothesis on :)

**Comment by Guria** [comment]
```js
const dialogPromises = {}

export openDialog(dialogKey) {
  let promise = new Promise((resolve, reject) => dialogPromises[dialogKey] = { resolve, reject })
  // TODO: throw error if dialogPromises[dialogKey] is not empty
  function action ({ output }) {
    promise.then(output.accept).catch(output.reject)
  }
  action.async = true
  return action
}

export closeDialog(dialogKey, accept) {
  return function action () {
    // TODO: make sure dialogPromises[dialogKey] is not empty and throw otherwise
    if (accept) {
      dialogPromises[dialogKey].resolve()
    } else {
      dialogPromises[dialogKey].reject()
    }
    delete dialogPromises[dialogKey]
  }
}
```

**Comment by jeroenverfallie** [comment]
I've had to do this in a larger project before, and while it's unclear in the debugger, it felt like the best solution at the time.

So, in my app, there's a vast amount of different interactions that require the user to be logged in.
Toggle favorite signal -> not logged in -> show login -> wait -> user logged in -> continue signal.
Now, there's 6 unique interactions that lead to this point in my app, and they can even be more complex as there's 2 way authentication, so it has to wait for a pusher message, etc etc.

I didn't want to queue the "continuation" of my signal, because there's so many different possibilites, and it became more complex to do this than to use the simple, but less "signal minded" solution like this:


```js
addSignals({
  favoriteToggled: [
      showLoginModal,
      waitForQueue('receivedUser'), {
        resolved: [toggleFavorite],
        rejected: []
      }
  ],
  loginModalSubmitted: [
    ...,
    set('state:user', ..),
    resolveQueue('receivedUser'),
    hideLoginModal
  ],
  loginModalClosed: [
    rejectQueue('receivedUser'),
    hideLoginModal
  ]
});
```

**Comment by gustavorino** [comment]
It makes sense, thank you!

Cerebral doesnt allow state mutation inside an Async action, right? Can you describe a good way to implement a progress bar?  (E.G : uploading a large file)

Thank you very much!

**Comment by Guria** [comment]
http://www.cerebraljs.com/documentation/cerebral-module-http has an example.
Join us at Discord, and ask such questions there. Issues are not intended for discussion topics.
