### ISSUE TITLE
Should multiple action outputs called throw an exception?

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral#309]
Hi, I'm wondering if calling two outputs in succession should throw an exception. Currently, only the last `output.method()` called within the action will fire. Not sure if this is by design or not. Would it make sense to throw an exception here?

```
      doSomething: [
        ({ output }) => {
          output.one({ payload: 'first' })
          output.two({ payload: 'second' })
          output.three({ payload: 'third' })
          output.one({ payload: 'first' })
        }, 
        {
          one: [({ input }) => { console.log('doing', input.payload) }],
          two: [({ input }) => { console.log('doing', input.payload) }],
          three: [({ input }) => { console.log('doing', input.payload) }]
        }
     ]


// running this signal will only log "doing first"
```

**Comment by christianalfoni** [comment]
Hi @awei01 ,

Yeah, it should throw an exception indeed. That said, with Cerebral2 you actually return a `path` from the function. Which means it is impossible to express multiple "outputs". Since Cerebral2 is already out in Alpha I think we should just let this one path. The migration path is not that big :)

**Comment by awei01** [comment]
ok, sounds good. looking forward to Cerebral2
