### ISSUE TITLE
Refactor tutorial docs and tutorial repos

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#337]
Docs lives now in https://github.com/cerebral/cerebral-website repo.
It is pretty easy to add new pages just by adding md files in content folder.
if you need to add new subfolder to side-nav define it at https://github.com/cerebral/cerebral-website/blob/v3/content/index.en.md
There is `npm star`t script there to test website locally.
Don't sure how to structure tutorial repo. But let's start with private sub package on monorepo like https://github.com/cerebral/cerebral/tree/master/packages/cerebral-demo

**Comment by fopsdev** [comment]
ok cool, will give it a shot on the weekend
it would be great to hav a tutorial structure ready soon
i'll put a proposal in here (if nobody else does) so we can discuss

**Comment by fopsdev** [comment]
# The Existing Tutorial Structure:
## Tutorial: Introduction
Concepts to learn: From State to View
## Tutorial: Next Step
Concepts to learn: From View to State or how to change State
## Tutorial: Advanced
Concepts to learn: Routing
## Tutorial: Get started
Concepts to learn: Immutable,Mutable, Viewlayers

# Goals for the new tutorials:
-  User should achieve something very quickly and easely. This also means that some concepts like scheme-parser, mutable, immutable, strict-mode will be left out. I really liked the "How would i handle" - part from the "old" website. so thats maybe the place for those guys.
- For those users coming from Angular or other MVC frameworks the advantages should be clear (eg. path change tracking against value/reference/whatever - checking, maintaining a complex app, ...)


# Proposal for the new Structure:
## Tutorial: Get started
(it's already done by christian, i might change a few things)
Concepts to learn: From State to View and Structuring your State, Viewlayers
Imo we could leave out immutable, mutable at this stage (its maybe more confusing for beginners)
## Tutorial: Update State
Concepts to learn: From View to State or how to change State, Debugger
Using Signals (also Async using http provider), Actions, Factories, Paths
## Tutorial: Providers
Concepts to learn: Create your own Provider
## Tutorial: Routing
Concepts to learn: Routing, it's just a provider an changing state
(so not really something new to learn here but this fact maybe underlines the simplicity of cerebraljs2 and should give the following impression to the user: "hey, i'm ready! :)" )

# Questions before i can start:
Should we use create-react-app for all the repos? I had quite a good experience with it
I could also create a branch for Inferno (which i personally prefer but has less users) and mention it for the peeps that would like to try it out. So i would focus on react for all the samples on the website.
will http provider also be under packages some fine day?
It's also a good thing that the  routing tutorial is at the end because  the api is not set in stone right now as i understand.
I'll use the newest versions to start (can't wait to check out the tagged templates (operators))

I'll start tomorrow later in the evening and i'm sure there will be more questions. Since i'm still a bit a "green banana" when it comes to webdev i would need for sure some pro tips when it comes to linting, codestyle, ... but this could be part of further iterations as well.

### So please drop your feedback here, it's mostly welcome.

**Comment by Guria** [comment]
Structure looks reasonable and fine for me.

> Should we use create-react-app for all the repos? 

Must

> will http provider also be under packages some fine day?

Yes. And forms as well. Which as another good case for tutorial.

> It's also a good thing that the routing tutorial is at the end because the api is not set in stone right now as i understand.

Right

**Comment by Guria** [comment]
React just added new [tutorial](https://facebook.github.io/react/tutorial/tutorial.html)
Might be we can lookup some interesting ideas from ther. Also we might mention it and expect user to learn it and show the same example upgraded to cerebral. What you say about it?

**Comment by fopsdev** [comment]
looks nice. i've already started cerebral tutorial without knowing that :)
maybe best if i just finish it and then we can iterate on it
btw. if i have some wip for cerebral-website  which i would like to have backuped, can i push it to a new branch? (i'm not a git jedi yet ;)

**Comment by Guria** [comment]
Yes, you should push to a new branch and create a PR. I will check if you have a rights needed a bit later

**Comment by fopsdev** [comment]
yeah doesn't look like i have permission:
```
git.exe push --progress "origin" tutorials

remote: Permission to cerebral/cerebral-website.git denied to fopsdev.
fatal: unable to access 'https://github.com/cerebral/cerebral-website.git/': The requested URL returned error: 403


git did not exit cleanly (exit code 128) (2703 ms @ 23/10/2016 12:44:58)
```

**Comment by Guria** [comment]
Accept an invitation to website repo and try again

**Comment by fopsdev** [comment]
status update:

![image](https://cloud.githubusercontent.com/assets/5448300/19643245/a6b71bca-99e9-11e6-8dd7-59e3176b544e.png)


following chapters are missing but i hope to deliver them during this week:
- advanced async actions
- providers
- routing

there is a repo for the tutorial as well here:
https://github.com/fopsdev/cerebral-tutorial

i planned to finish the tutorial until end of this week

**Comment by fopsdev** [comment]
btw. it's an incremental tutorial where the user build up an app step by step

**Comment by christianalfoni** [comment]
This stuff looks really great! Great job @fopsdev! And huge thanks :)

**Comment by fopsdev** [comment]
need a bit of more time because of my windows-node-env var-bash-linux- dance ;)

**Comment by fopsdev** [comment]
ok i'm having a few questions now:

in the tutorial i'm using a toast-component that displays messages to the user.
## so the first version was:
https://github.com/fopsdev/cerebral/blob/tutorial/packages/cerebral-website-tutorial/parts/08_customaction_challenge/src/index.js
## and then in chapter 9 we improved (its part of the tutorial) it to:
https://github.com/fopsdev/cerebral/blob/tutorial/packages/cerebral-website-tutorial/parts/09_using_async_actions/src/index.js
**-> this should help to explain simple async flows and is part of the big picture that the users should get. the toast component is imo a really nice andidate to demonstrate that. by reading the full tutorial you maybe can understand my decision better :)**
## and then in chapter 10 we discover a flaw of this component:
https://github.com/fopsdev/cerebral/blob/tutorial/packages/cerebral-website-tutorial/parts/10_1_using_path/src/index.js

when looking at the signal:
```js
getRepoInfoClicked: [
      set(state`repoName`, input`value`),
      ...showToast('Loading Data for repo: @{repoName}', 2000),
      GetData,
      set(state`data`, input`result`),
      ...showToast('How cool is that. @{repoName} has @{data.subscribers_count} subscribers and @{data.stargazers_count} stars!', 5000, "success")
    ]
```
that means that it displays a message "Loading Data..." and then waits for 2 seconds and then removes the message and then calls GetData(...).

### but what we really want is:
**showToast(...)**, -> display message and immediately go on with *GetData(...)*
**GetData {...}**

*please be aware that meanwhile the toast component is a stackable toast component that can handle multiple messages very nicely*

**Comment by Guria** [comment]
```js
function showToast (message, milliseconds = 8000, type) {
  const id = Date.now()
  function action ({input, state, path}) {
    const msg = message || input.message
    state.unshift('toast.messages', { msg, type, id })
    return new Promise(function(resolve, reject) {
      window.setTimeout(function() {
        resolve(path.timeout({}))
      }, ms)
    })
  }
  action.displayName = 'showToast'
  return [action, {timeout: [
    // we need filter, because messages has different timeouts
    // pop could remove still valid one
    filter(state`toast.messages`, (message) => message.id !== id)
  ]}]
}

function GetData({input, state, http, path}) {
  return http.get("/repos/cerebral/" + input.value)
    .then(({result}) => path.success({ result }))
    .catch(error => path.error({ error }))
}

getRepoInfoClicked: [
  set(state`repoName`, input`value`),
  [
    ...showToast('Loading Data for repo: @{repoName}', 2000),
    GetData, {
      success: [
        set(state`data`, input`result`),
        ...showToast('How cool is that. @{repoName} has @{data.subscribers_count} subscribers and @{data.stargazers_count} stars!', 5000, "success")
      ],
      error: [
        ...showToast('failed to make request', 5000, "error")
      ]
    }
  ]
]
```

**Comment by fopsdev** [comment]
Ok, thanks a lot @Guria 

But it still waits for 2000 ms now before executing GetData(...)  :(

**Comment by Guria** [comment]
It shouldn't. Have you used array?

**Comment by fopsdev** [comment]
ah yeah, that helped :)

but now i'm thinking i'm running into a bug (console):
```
events.js:160 Uncaught TypeError: Cannot read property 'accepted' of undefined
```
i also resolve the id now to the timeout chain:
```
import React from 'react'
import { render } from 'react-dom'
import { Controller } from 'cerebral'
import App from './components/App'
import { Container } from 'cerebral/react'
import Devtools from 'cerebral/devtools'
import { state, set, input, filter } from 'cerebral/operators'
import HttpProvider from 'cerebral-provider-http'

const controller = Controller({
  devtools: process.env.NODE_ENV === 'production' ? null : Devtools(),
  state: {
    title: 'Hello from Cerebral2!',
    appTitle: 'Cerebral Tutorial App',
    toast: {
      messages: []
    },
    originalValue: '',
    extendedValue: '',
    repoName: 'cerebral',
    data: {}
  },
  signals: {
    buttonClicked: [
      ...showToast('Button clicked!', 1000)
    ],
    saveButtonClicked: [
      set(state`originalValue`, input`value`),
      myAction1,
      myAction2,
      myAction3,
      ...showToast()
    ],
    getRepoInfoClicked: [
      set(state`repoName`, input`value`),
      [
        ...showToast('Loading Data for repo: @{repoName}', 2000),
        GetData,
        {
          success: [
            set(state`data`, input`result`),
            ...showToast('How cool is that. @{repoName} has @{data.subscribers_count} subscribers and @{data.stargazers_count} stars!', 5000, "success")
          ],
          error: [
            set(state`data`, input`result`),
            ...showToast('Ooops something went wrong: @{data.message}', 5000, "error")
          ]
        }
      ]
    ]
  },
  providers: [
    HttpProvider({
      baseUrl: 'https://api.github.com'
    })
  ],
})

function myAction1({input}) {
  input.value += ' extended by myAction1'
}

function myAction2({input, state}) {
  input.value += ' and also by myAction2'
  return ({
    aKeyAddedByMyAction2: 'testvalue'
  })
}

function myAction3({input, state}) {
  input.value = input.value.toUpperCase()
  input.message = input.value
  state.set('extendedValue', input.value)
}


function GetData({input, state, http, path}) {
  return http.get("/repos/cerebral/" + input.value)
    .then(response => {
      return path.success({
        result: response.result
      })
    })
    .catch(error => {
      return path.error({
        result: error.result
      })
    })
}

function showToast(message, milliseconds, type) {
  function action({input, state, path}) {

    let ms = milliseconds
    let msg = message || input.message
    // replace the @{...} matches with current state value
    let reg = new RegExp(/@{.*?}/g)
    var matches = msg.match(reg)
    if (matches) {
      matches.forEach(m => {
        let cleanedPath = m.replace("@{", "").replace("}", "")
        msg = msg.replace(m, state.get(cleanedPath))
      })
    }
    if (!ms) {
      ms = 8000
    }
    let newMsg = {
      msg: msg,
      type: type,
      id: Date.now()
    }
    state.unshift('toast.messages', newMsg)
    return new Promise(function(resolve, reject) {
      window.setTimeout(function() {
        console.log(newMsg.id)
        resolve(path.timeout({
          id: newMsg.id
        }))
      }, ms, newMsg)
    })
  }
  action.displayName = 'showToast'

  return [action, {
    timeout: [
      set(state`extendedValue`, input`id`),
      filter(state`toast.messages`, (message) => message.id !== input`id`)
    ]
  }]


}
render((
  <Container controller={ controller }>
    <App />
  </Container>
  ), document.querySelector('#root'))
```

**Comment by Guria** [comment]
I have misused filter operator. Rewrite it using state.set with filterd array

**Comment by fopsdev** [comment]
couldn't figure it out with using filter.
so i went back to using 
```pop(state`toast.messages`)```
 i don't think it's an issue  because of the wrong element gets removed because overall viewing time for the user is fine
i can see now in the debugger that it nicely removes the messages, but the ui doesn't change anymore
![pop](https://cloud.githubusercontent.com/assets/5448300/19841229/65483b46-9f08-11e6-98b2-170207abcadc.gif)

**Comment by fopsdev** [comment]
Good morning Guys ;)

I have now simplified the solution because i think it's not necessary to output to a path for this very simple usecase.

### Simplify the return value of the factory to not include paths

```
 action.displayName = 'showToast'
  return [action,
    pop(state`toast.messages`)
  ]
```

I had it like that somewhen yesterday afternoon, but it didnt work so i've moved on
Now i went back to it because i cannot find another solution which works.

My code is based on information from the v2 website:
https://cerebral.github.io/cerebral-website/concepts/02_signals.html

``` To define async execution of an action you simply return a promise from it. ```
And
``` With the example above, where we returned an object from getData, the next action would have result available to it ```

That sample didn't use Paths and thats great because if we could do the same the tutorial would become much more simpler.

Thanks for the help so far but now I'm running in circles here. Could please somebody pick up my code an run it to see the dilemma? :)

**Comment by fopsdev** [comment]
after checking it again it's clear to me why it doesn't work
```
return [action,
    pop(state`toast.messages`)
  ]
```
will result in a chain like:
```

      set(state`repoName`, input`value`),
      [
        ...showToast('Loading Data for repo: @{repoName}', 2000),
        pop(state`toast.messages`),
        GetData,
        {
...
```
And because the second [ will indicate that all the containing actions will be executed at the same time
--> so yeeeeah i've got that :)

**Comment by fopsdev** [comment]
I've updated the code again to resolve to a path.
this still leaves the question like 3 posts above:
why doesn't the UI change (state changes fine) ?

**Comment by fopsdev** [comment]
fyi:
had a chat with @Guria , we've moved the package to:
https://github.com/cerebral/cerebral/tree/tutorial

**Comment by fopsdev** [comment]
Ok found a possible issue:
Had to add:
https://github.com/cerebral/cerebral/blob/flushFunctionEnd/packages/cerebral/src/Controller.js#L54
To make the UI render as well when state changes where done within an path-chain
At least this solves my issue.
For the taostRemove() - Story i have created an action like instructed by @Guria which removes the correct msg from the array, Thanks a bunch for the hint!

**Comment by fopsdev** [comment]
with great joy i can announce that the first iteration of the tutorial is finished

**Comment by Guria** [comment]
Thanks for great tutorial. I have merged it already. Lets keep iterating on it.
