### ISSUE TITLE
move generic operators to function-tree

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#370]
I think that common operators, which are not strictly bound to cerebral(ish) tasks, might be better off being maintained in the function-tree package. Chances are that other function-tree implementations will need some of that magic too :)

We could still add references in the cerebral package so that you can keep importing from `cerebral/operators` for better ease of use.

Here's what I think should be moved - whatcha thinkin?
- when
- set
- copy

It appears that set and copy have merge into one.. so just set would be sufficient. Set would work best when `target:path.to.prop` would point to `context.target.to.prop` ... that way you can access anything that's provided on the context.

**Comment by Guria** [comment]
Would you like to try make a pr with example usage in function-tree-demos package?

**Comment by christianalfoni** [comment]
I actually tried doing this in initial function-tree implementation, but it is very difficult to do generically. The reason is that sometimes you want operators to do a "set" of some sort, other times you want it to be a "get".... For example `set(state`foo.bar`, 'bar')` means that we want to "state.set('foo.bar', 'bar')"... but for other things that might be "something.foo.bar = 'bar'"... my conclusion is that operators are too specific to project.

But that was just my take on it, if you implementation details on how to make them generic please throw them at us :)

**Comment by henri-hulski** [comment]
BTW It's now
```js
target`path.to.prop`
```

**Comment by maxfrigge** [comment]
Mhh.. hadn't thought of `state.set('path', value)` in contrast to just `state.path = value` @christianalfoni - how are you going to handle this in cerebral.. have a case for `target === 'state'`? Do deal with this more generically there could be a convention that check `typeof target.set` ... but that will only help for so long I guess :)

@henri-hulski Yes.. I read it discord. I have just played with the idea in pseudo code, but couldn't really see the benefit over having e.g. `target:path.to.prop` as a pure string. What exactly where the reasons to favour this again?

**Comment by Guria** [comment]
Close it as noop for now. Feel free to continue discussion or make request if you will find it useful.
