### ISSUE TITLE
Connect currying does not work properly [cerebral@2]

### ISSUE THREAD

**Issue by etienne-dldc** [cerebral/cerebral#468]
## The code I'm interesting in

`src/viewFactories/connect.js`:
```js
export default HOC => function connect (paths, passedSignals, injectedProps, passedComponent) {
  let component = passedComponent
  let signals = passedSignals
  let props = injectedProps

  if (arguments.length === 3) {
    component = props
    props = null
  } else if (arguments.length === 2) {
    component = signals
    signals = null
  }

  if (!component) {
    return function (decoratedComponent) {
      return HOC(paths, signals, props, decoratedComponent)
    }
  }

  return HOC(paths, signals, props, component)
}
```

## Problem

The `connect` function contains this bit of code: 
```js
  if (!component) {
    return function (decoratedComponent) {
      return HOC(paths, signals, props, decoratedComponent)
    }
  }
```
which seems to allow currying and so using connect as a Decorator (or in `compose` for Stateless component).

But this code does not work because before it, arguments are re-assigned depending on `arguments.length` :
```js
  if (arguments.length === 3) {
    component = props
    props = null
  } else if (arguments.length === 2) {
    component = signals
    signals = null
  }
```
Because of that the following code **does not works**
```js
connect(paths, signals)(Component);
// or
@connect(paths, signals)
class Component {}
// or
compose(
  connect(paths, signals)
)(Component);
```
In this case the `arguments.length === 2` condition is `true` and signals are sets in component... and `HOC` is called with the following argument `HOC(paths,null, null, signals)` which is 👎.

This mean the only way to make currying works is the following :
```js
@connect(paths, signals, props, null)(Component);
```
Which is quite annoying...

## Possible solution

I think a better API would be the same as `redux` : alway returning a HOC function instead of passing the component as the last argument.

## Note

I'm using `cerebral@next` which resolve to `cerebral@2.0.0-0-alpha.5a3d129e`.

**Comment by christianalfoni** [comment]
Hi there and thanks for a very well written issue! :)

I completely agree with you from a technical perspective, but this was actually a choice we made... though of course it should be challenged :)

### The reasoning behind it
Though currying is a really cool concept, it is not a common thing to use (Of course no facts to back this up), but it is definitely not one of the first concepts you are introduced to in programming. And in the world of web development, currying is pretty far out there. So one of the concerns is making people understand it.

The second reason is that though currying is powerful, I do not see how you would ever use it with components in Cerebral world. The reason is that connecting a component is not a generic thing. You have some state and signals you want a **single** component to handle. Multiple components handling the same state and/or signals does not make any sense in my experience, but please correct me with examples here :)

### Conclusion
So it has basically been favoring familiar syntax:

```js
connect({
  bar: 'foo.bar'
}, 
  function MyComponent (props) {

  }
)
```

Rather than introduce a complex programming subject (currying) and require syntax that does not really make that much sense for for common developers:


```js
connect({
  bar: 'foo.bar'
})(
  function MyComponent (props) {

  }
)
```

**Comment by etienne-dldc** [comment]
Thanks for this quick response 👍 

I understand your arguments and if it's a choice then keep the API this way.
But then you should probably remove the `if (!component)` code because it's useless.

Also, if someone else is interested, converting the `connect` function into a decorator is very simple:
```js
function connect(...args) {
  return (component) => cerebralConnect(...args, component);
};
```
So I can live with that :)

**Comment by Guria** [comment]
Let's keep open until solved in either way

**Comment by Guria** [comment]
I think separate export for decorator is a good way to go. Would you like to make a PR?

**Comment by christianalfoni** [comment]
@etienne-dldc Yeah, I see your point now! But!

We could change the ifs rather... Actually check for it being a component

```js
if (arg instance of React.Component) {}
```

That way component might be false and decorator will work. This is core issue, right? :)

**Comment by etienne-dldc** [comment]
@christianalfoni I think @Guria 's solution might be better because it's more simple and does not need to import all possible types of component (React and Inferno for now).

@Guria Yes, I will make a PR soon.

**Comment by Guria** [comment]
@christianalfoni instance of React.Component will no work for SFC.

**Comment by christianalfoni** [comment]
I guess this can be closed?

**Comment by Guria** [comment]
It will be closed automatically by github
