### ISSUE TITLE
Computed state layers

### ISSUE THREAD

**Issue by maxfrigge** [cerebral/cerebral#560]
As proposed by @garth one could consider using computed layers on top of the state. 

Let's collect thoughts here.

**Comment by maxfrigge** [comment]
Thoughts I had were:

- could decreases visibility of dependencies
- would eliminate the risk of circular dependencies

**Comment by garth** [comment]
From the point of view of the debugger, it would be nice to see the final state (state + computed layers) and the step down through the layers until you reach the original state.

Here's just a rough idea of what connect could look like (just to get the conversation started)

```js
connect([
  { foo: 'foo.path' },
  { foo: augmentFoo() },
  { foo: sortAugmentedFoo() }
], {
  signal: 'foo.signal'
}, (stateProps, signalProps, ownProps) => ({
  originalFoo: stateProps[0].foo,
  foo: stateProps[2].foo
}), (props) => {
  ... 
})```

**Comment by Guria** [comment]
Can't get what it really gives us. Could you give example on how you will use it

**Comment by maxfrigge** [comment]
@garth So you wanted to use those layers on a per component base and not for the globale state object?

**Comment by garth** [comment]
@maxfrigge yes, I think that the control should stay with connect so that you maintain visibility of what is going on (no magic), also each component may need to compose computeds in different ways which may conflict in a global approach.

@Guria maybe it's best to think about what we are trying to solve:

### Level 0
I have an unordered set of people
```js
{
  '1': { fistName: 'c', lastName: 'd', dob: new Date() },
  '2': { fistName: 'a', lastName: 'b', dob: new Date() }
}
```

### Level 1
Then I have a computed that will add `fullName` and `age`
```js
{
  '1': { fistName: 'c', lastName: 'd', dob: new Date(), fullName: 'c d', age: 0 },
  '2': { fistName: 'a', lastName: 'b', dob: new Date(), fullName: 'a b', age: 0 }
}
```

### Level 2
Then I have a computed that will sort a set by given properties (eg `['fullName']`)
```js
[
  { fistName: 'a', lastName: 'b', dob: new Date(), fullName: 'a b', age: 0 }
  { fistName: 'c', lastName: 'd', dob: new Date(), fullName: 'c d', age: 0 }
]
```

### There are a number of things that I want to achieve

1. If I add/remove a person the other Level 1 computeds should not re-run except for the newly added item. The level 2 computeds should re-run.
2. If I change level 2 computeds (eg change sort direction) level 1 computeds should not re-run.
3. I can reuse computeds (such as sort) on regular state or computed state
4. Computeds should be composable
5. Computeds should be clearly defined via connect (no magic)
6. It would be nice to be consistent with other parts of cerebral (eg signal chain)

### Alternative solution

```js
connect([
  {
    originalFoo: 'foo.path',
    foo: [
      augmentFoo(),
      sort({ foo: 'foo' })
    ]
  }
], {
  signal: 'foo.signal'
}, (stateProps, signalProps, ownProps) => ({
  originalFoo: stateProps.originalFoo,
  foo: stateProps.foo
}), (props) => {
  ... 
})
```

**Comment by maxfrigge** [comment]
I think it could help to see the "original" syntax.

```js
connect({
  originalFoo: 'foo.path',
  augmentedFoo: augmentFoo(),
  sortedFoo: sort({ foo: 'foo' })
}, {
  signal: 'foo.signal'
}, (stateProps, signalProps, ownProps) => ({
  originalFoo: stateProps.originalFoo,
  foo: stateProps.foo
}), (props) => {
  ... 
})
```

**Comment by christianalfoni** [comment]
Here are my cents after thinking about this:

1. I think the current computed concept is really good. Since computeds works exactly like components we can create a similar list in debugger as components. Instead of a list of state paths and what components use it, it can be a list of computeds (using function name as name), any props passed to it and what values they currently return. Super simple to implement

2. When it comes to "define them one place" this can be done as simply as creating a module and define them there:

```js
export default {
  computeThis: Computed(),
  computeThat: Computed()
}
```

3. About layers... personally I have no experience with extensive use of computeds. We use simple filters and lookups in our project. But having a layer type of state definition has a huge cost in terms of implementation. It really complicates how state path values and the state dependencies of a component is evaluated... and it seems to be functionality for a very small share of Cerebral apps. That said! I want to challenge you to create a "layer concept" based on current API, using factories or similar patterns ;-) we should at least explore that first, as it will have a big cost to implement it

Btw... after discussions I found a way to avoid doing the "force cache busting", though need to figure out best way to handle it... but it is possible. The reason is actually @gaspard refactor where the Model is actually what grabs the value from the computed. The Model knows if any paths has already changed and can verify that with the computed before trying to grab the value.... pretty cool :)

**Comment by Guria** [comment]
@garth it is already solvable now I am sure:
```js
// state tree
{
  persons: {
    '1': { fistName: 'c', lastName: 'd', dob: new Date() },
    '2': { fistName: 'a', lastName: 'b', dob: new Date() }
  }
}

const fullName = Computed(
  (personId) => ({
    fistName: `person.${personId}.fistName`,
    lastName: `person.${personId}.lastName`
  }),
  ({fistName, lastName}) => [fistName, lastName].join(' ')
)

const age = Computed(
  (personId) => ({dob: `person.${personId}.dob`}),
  ({dob}) => return now - dob
)

const Person = connect(
  (personId) => ({
    person: `person.${personId}.*`,
    fullName: fullName.props({personId}),
    age: age.props({personId}),
  }),
  {},
  ({person: {firstName, lastName, dob}, fullName, age}}) => {
    return {firstName, lastName, dob, fullName, age}
  },
  function Person ({firstName, lastName, dob, fullName, age}) {
    return ...
  }
)

<Person personId={1} />
```

**Comment by garth** [comment]
# 💡💡💡

After some discussion and though, it occurs to me that computeds may now be irrelevant and no longer required now that we have the new `mergeProps` function!

```js
var augmentFoo = memoize((foo) => fooWithBells);
var sortFoo = memoize((foo) => foo.sort());

connect([
  {
    foo: 'foo.path'
  }
], {
  signal: 'foo.signal'
}, (stateProps, signalProps, ownProps) => ({
  originalFoo: stateProps.foo,
  foo: sortFoo(augmentFoo(stateProps.foo)) // sortFoo and augmenFoo are memoized functions
}), (props) => {
  ... 
})
```

We can now use a combination state and regular props to pass into memoized functions. The only issue is when to clear the memoized cache so that we don't have memory leaks.

Maybe we could just remove the "connect" part of Computed and use the same cache with the same cache disposal rules. I think that would work.

Either way we end up with a much simpler setup for Computeds which now work the same in actions and in components with no magic!

🤦🤦🤦

**Comment by garth** [comment]
@Guria You are right, it is solvable now, I am using a lot of nested computeds in my current project but it is hard, especially when you are trying to compose computeds. This is why I am looking for a simpler abstraction.

@christianalfoni / @Guria with my previous suggestion, maybe this can even be done outside cerebral and just hook into the controller to invalidate the cache?

**Comment by christianalfoni** [comment]
I think this is super interesting @garth . Always favour simplifying things!

The big challenge here is to identify usage of memoized functions... cause they just return values, we have no control of when they are used.

Also now "mergeProps" function just puts stuff on props, they are not picked up by Cerebral in any way, so it does not understand the returned values there... even if they were computeds.

But... lets think about this. We have one huge advantage with Cerebral and that is components depend on specific state and only run when the state actually changes. What if we throw caching out the door, because we already have the component as the optimizer:

```js
var augmentFoo = (foo) => fooWithBells;
var sortFoo = (foo) => foo.sort();

connect([
  {
    foo: 'foo.path'
  }
], {
  signal: 'foo.signal'
}, (stateProps, signalProps, ownProps) => ({
  originalFoo: stateProps.foo,
  foo: sortFoo(augmentFoo(stateProps.foo)) // sortFoo and augmenFoo are functions
}), (props) => {
  ... 
})
```

In this case the only time these functions are run is when `foo.path` actually has an update. Our Component is the wrapper to optimize when the functions run. Of course sometimes a component depends on other state as well, but still... compared to always update on every state change we are completely within the "range of unnecessary computation" IMO.

And in actions you just do:

```js
function someAction ({state}) {
  const foo = state.get('foo.path')
  const sortedFoo =  sortFoo(augmentFoo(foo)) 
}
```

I do not think it is an issue at all. If you actually need to optimize, just create a memoization function like @garth suggests.

**Comment by gaspard** [comment]
@christianalfoni no, the functions can run much more if the component has more then one state path...

@garth I think composition should be handled outside of Cerebral:

```js
export const composedComputed ( paths, ...functions ) {
  return Computed ( paths, compose ( functions ))
}

export const compose (functions) {
  return functions.reduce((props, fun) => fun(props))
}

// And then you use it like
connect({
  foo: composedComputed ( { foo: 'foo.path' }, addBells, sort )
})
```

**Comment by garth** [comment]
@christianalfoni I think that the caching is important, especially for apps where a computed may be used in many components and/or actions.  Maybe we can just use the existing ComputedFactory but remove the state connect and just use props? then it will work.

@gaspard I have come to a similar conclusion. Keep cerebral simple (which has always been a goal for cerebral).

**Comment by christianalfoni** [comment]
@garth @gaspard 

Hm, I do not think it is good to remove state paths from Computed cause it complicates:

```js
connect({
  someComputedDep1: 'some.dep',
  someComputedDep2: 'some.other.dep'
}, {}, (stateProps) => ({
  foo: someComputed({stateProps.someComputedDep1, stateProps.someComputedDep2})
})
```

Whereas you can just do:

```js
connect({
  foo: someComputed
})
```

I would state that is the common case. The next level of complexity is where you pass dynamic props, but often this is related to computeds not being able to compose them at instance time themselves. But with the change in https://github.com/cerebral/cerebral/issues/568 that will now be possible:

Taken from our project:
```js
Computed({
  activities: 'app.activities.**',
  challengeActivityKeys: challengeType === 'household' ? 'challenge.householdChallenge.data.activities' : 'challenge.teamChallenge.data.activities'
})
```
is not necessary any longer, cause we can just do:
```js
Computed({
  activities: state`app.activities.**`,
  challengeActivityKeys: state`challenge.${state`challenge.type`}.data.activities'
})
```

Which I would also expect is quite common.

And then we have highest level of complexity, which is where you have to pass in props for some reason... so I would rather make the two scenarios mentioned the most approachable. And I am very certain we can find a way to compose computeds together :) Even with : `oneComputed.compose(someOther, andOther)`... or something. Just not familiar with the scenario :)

**Comment by garth** [comment]
@christianalfoni I think that we can leave the existing computeds implementation as is. So long has we have enough info in the controller/state change events we can experiment with alternative implementations outside of cerebral core.

Though I do believe, the more I consider, that the correct place for computeds in the connect args should be in the mergeProps.

**Comment by christianalfoni** [comment]
@garth Yeah, let us make sure we open up for experimentation here. Maybe new approach to computeds will be the hot thing in Cerebral 3 :)

But now your layers suggestion dawned on me Garth... I think a good example is relational data. I had a discussion with @fopsdev on this.

Let us say you have a **Transaction** with an **employeeId** and **vehicleId**. We do not encourage using classes, so you would think of a Computed as a class instead:

```js
const Transaction = Computed(...)
```

So when you want to show a transaction you connect give the computed the ID of the transaction:

```js
connect(({transactionId}) => ({
  transaction: Transaction.props({transactionId})
})
```

Now! The thing is that you can not grab the employee or the vehicle without the transaction itself and we only have the ID of it. So:

```js
const Transaction = Computed([{
  transaction: state`app.transactions.${props`transactionId`}`
}, {
  employee: state`app.employees.${props`transaction.employeeId`}`,
  vehicle: state`app.vehicles.${props`transaction.vehicleId`}`
}], ({transaction, employee, vehicle}) => {
  return Object.assign({}, transaction, {employee, vehicle})
})
```

If this is what you mean @garth , it makes sense to me to implement and technically it is no problem :)

**Comment by garth** [comment]
Yes, relational data is a good example. We often have and entity type and set of entities that need to be merged.

In this case we often get a collection of entityId and need to resolve that to one or more entityTypeId and then reduce.

**Comment by christianalfoni** [comment]
@garth Thinking about writing a "best practices" on relational data. Is this how you approach an entity with multiple relationships?

```js
const User = Computed({
  user: state`users.${props`userId`}`,
  projects: state`projects`
}, ({user, projects}) => {
  return Object.assign({}, user, {
    projects: user.projectIds.map((id) => projects[id])
  })
})
```

If not, how would you approach it?

**Comment by christianalfoni** [comment]
Okay, so I have been playing around with computeds a lot the last few days, thinking, testing implementations and syntax. We want to do so many different things and now I think we are moving towards building on top of something that is fundamentally wrong.

Let me show you some examples of what I have come up with and then some arguments why I think we need to move this way.


```js
// Simple, "declarative"... like action factories
connect({
  user: state`user`
}, ...)

// Low level, "imperative"... like actions
connect(({props, getState, getSignal}) => {
  return {}
}, ...)

// Allow multiple
connect([
  ({props, getState, getSignal}) => ({}),
  {}
], ...)
```

So, why did I end up with this API? Let us go through some scenarios where you need to grab state:

#### 1. Just grab some state
```js
connect({
  user: state`app.user`
}, ...)
```

#### 2. Just grab some state based on state
```js
connect({
  item: state`items.${state`currentItemKey`}`
}, ...)
```

#### 3. Filter stuff
This is where we need to go "low level" and imperative. All calls to `getState` will be tracked as a state dependency.

```js
connect(({getState}) => {
  const list = getState('app.list')
  const filter = getState('app.filter')

  return {filteredList: list.filter(item => item === filter)}
}, ...)
```
This can rather be expressed as:

```js
const filteredList = ({getState}) => {
  const list = getState('app.list')
  const filter = getState('app.filter')

  return {filteredList: list.filter(item => item === filter)}
}

connect(filteredList, ...)
```

Or if you need to add additional state:

```js
connect([
  filteredList,
  {
    user: state`app.user`
  }
], ...)
```

#### 4. Memoize heavy computation
There is not need to handle this in Cerebral. You can just memoize whatever you want:

```js
import memoize from 'memoizee'

const filterItems = memoize((items, filter) => { ... })

export default filteredItems ({getState}) {
  return {filteredItems: filterItems(getState('app.items'), getState('app.filter'))}
}
```

**memoizee** for example allows you to set a timeout on the cache or clear it manually whenever. this could be on component umount, during a signal execution etc.

#### 5. Create relational dependencies
```js
connect(({getState, props}) => {
  const user = getState(`app.users.${props.userKey}`)
  const projects = user.projectIds.map(id => getState(`app.projects.${id}`))

  return {user, projects}
}, ...)
```

Could be expressed as:
```js
connect([
  {
    user: state`app.users.${props`userKey`}`
  },
  userProjects
], ...)
```

#### 6. Get state in actions
```js
function someAction ({state}) {
  state.get(filteredList, {foo: 'bar'})
}
```
Using a function to get state will match signature `({getState, props}) => {}`.

### Summary
Conceptually this API matches how we think declarative action factories VS imperative actions. Declarative connect object VS imperative connect function. The only way to solve any kind of exact state dependency is to use an imperative API, it is not possible to do the "user projects" above with current API.

Also caching is such a huge pain and very difficult to manage in a good way. There are so many things happening under the hood to make these computed work. Also the fact that we want to use them cross **connect** and **actions** makes it very difficult... currently `state.compute` is a memory leak.

This API allows us to solve any kind of state dependency and compose it together with whatever, using the array. Caching is handled where needed. 

This is a relatively big breaking change, but computeds is the one thing Cerebral does not handle very well, because you can not express any kind of state dependency like you want. It is this thing we have been building on top of, instead of rethinking it completely with all the experience this far.

You could even create compositions like this now:

```js
connect([
  user,
  userProjects,
  userNotifications
], ...)
```

Okay, let me know what you think :)

**Comment by garth** [comment]
@christianalfoni One of the earlier discussions we had was to consider making computed "chains" in a similar way to the current action "chains". Your proposal brings us very close to this, which is a good thing!

But just to be sure, in actions we would also want chains to work in the same was as `connect`.

```js
function someAction ({state}) {
  state.get([user, userProjects], {userKey: '1'})
}
```

I also agree to keep memoize separate (as you know I also came to the same conclusion), but I think that we need to offer a good, clear example of how to do it.

**Comment by Guria** [comment]
@christianalfoni same question as with new tags suggestion https://github.com/cerebral/cerebral/issues/568#issuecomment-267825235

**Comment by fopsdev** [comment]
not sure if it helps here.
but thats how i use computeds to:
- filter
- sort and page
relational data
https://gist.github.com/fopsdev/9c34c81c3f8385126a66de3e6cfe0ae9

performance is quite ok right now, so that's the only thing i'm concerned about when redoing computeds

**Comment by gaspard** [comment]
First, I like the idea to remove computed and make things simpler. But I think we should consider simplifying this `connect` api. I think it is becoming way too complex with optional arguments, things that can be objects or functions or arrays of objects, arrays of functions, etc. This will prove confusing (and hard to type debug). So, my idea is this:

- connect takes **a single object as first argument**
- this object **only** contains functions that can resolve to a value when called with a context (like tags do)

So now, a computed looks like a tag function from the outside (except it does not set `target` or `path`). BTW, it makes sense that tags use `getState` in the same way (for caching purpose and overall api simplification).

```js
const filteredList = ({getState}) => {
  const list = getState('app.list')
  const filter = getState('app.filter')

  return { value: list.filter(item => item === filter)} // note: "value" here
}

connect({
  filteredList, // just a function
  projects: projects`${props`userId`}`, // user created factory
  foo: state`foo.thing`
}, ...)
```

Like this, we do not need the complicated connect api and we (gently) encourage users to create their own factories based on tags (if they need such factories).

What do you think ?

**Comment by christianalfoni** [comment]
@garth Yes, indeed

@Guria Yes, this can be deprecated

@fopsdev The great thing about the new approach is that for example your filter will no longer update when non related employees are updated. Since you will `getState` on the specific employees, only when those change the filter will update. Just an example of how more specific state dependencies will optimize

@gaspard Yeah, I like how it looks, cause it keeps things simple and unchanged really. Since we remove computed we can actually identify a function on the key as "manual state retrieval". And we could also introduce:

```js
connect({
  augmentedItem: compose(currentItem, augmentItem)
}, ...)
```

Where compose just passes in the extended props for each function (and of course getState and getSignal).

Another note is that I think we should get Tags fix in first, then we can make this fix. Cause there will be too much deprecation code... so messy :)

**Comment by gaspard** [comment]
@christianalfoni not much coding time with all the family events and stuff, will try to fix demo today to stop blocking this.

**Comment by christianalfoni** [comment]
@gaspard That is awesome, I will start refactoring our project as well with the new syntax, preparing it :)

**Comment by christianalfoni** [comment]
Btw, I just figured out that we can actually optimize these functions even more. When a component is asked to render again we can pass in the flushed changes object. That way the component, can figure out if any attached "state functions" needs to run again. That means you can attach multiple functions, also normal declarative state deps, and they will only run again if their exact state dependencies has changed. Anyways... will get more into it later :)

**Comment by garth** [comment]
@christianalfoni Just reviewed the latest proposal again. Computed state functions start to look very much like actions... What if they were the same?

```js
// some action chain
export default [
  { user: state`app.user` },
  userProjects, // readonly cachable action/computed
  updateUserProjects
]
```

Then we can use the same in connect

```js
// some view
connect([
  { user: state`app.user` },
  userProjects
], () => {
  // render user projects
})
```

For this to work we simply need the computed signature to look the same as action

```
export default function userProjects({ input: { user }, state }) { // input could be an alias to props
  return {
    projects: user.projectIds.map(id => state.get(`app.projects.${id}`))
  }
}
```

This setup would mean that we wouldn't need to pass computed functions into state within actions, we just insert the computeds into the action chain before the data is needed. It also means that the same optimisations can be applied.

**Comment by christianalfoni** [comment]
I would say this is solved :)
