### ISSUE TITLE
passing props to tags and computeds

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#631]
I have a tag exported
```js
const taskName = state`${tasks}.${props`itemKey`}.${name}`
```
it fits great with component like:
```js
const Task = connect(
  {
    taskName
  },
 TaskView
)

taskList.map(itemKey => <Task itemKey={itemKey} />)
```
but sometimes i want to create  component mapped to some special key
```js
const draftTaskName = taskName.props({itemKey: '$$draft'})

const TaskDraft = connect(
  {
    taskName: draftTaskName,
    fieldChanged
  },
  ({taskName, fieldChanged}, {}, resolve) => ({
    children: <input value={taskName} onChange={e => fieldChanged({ field: resolve.path(draftTaskName), value: e.target.value })} />
  }),
  TaskDraftView
)

<TaskDraft /> // there is no good reason to pass itemKey='$$draft' because it is only supported value
```
the same applies to compute as well
```js
import {compute} from 'cerebral'
import {state, props} from 'cerebral/tags'
import {categories, tasks, categoryRef, trashCategory} from '../constants'
import categoriesByParent from './categories-by-parent'

function collectChilds (tasksMap, categoriesByParent, itemKey, childs = {[categories]: [], [tasks]: []}, level = 0) {
  childs[categories].push(itemKey)
  ;(categoriesByParent[itemKey] || []).forEach(ref => {
    collectChilds(tasksMap, categoriesByParent, ref, childs, level + 1)
  })
  if (level === 0) {
    // collect orphaned tasks
    childs[tasks] = Object.keys(tasksMap).filter(ref => childs[categories].indexOf(tasksMap[ref][categoryRef]) >= 0)
    if (itemKey === trashCategory) {
      // exclude virtual category from result
      childs[categories].shift()
    }
  }
  return childs
}

export default compute(
  state`${tasks}.**`,
  categoriesByParent,
  props`itemKey`,
  (tasksMap, categoriesByParent, itemKey) => collectChilds(tasksMap, categoriesByParent, itemKey)
)
```
usually it would used as is on component extracting itemKey from component props.
But in one particular place I need it with predefined `{itemKey: trashCategory}`.

Factories is possible solution but it makes harder to reason what we import tag/computed or tag/computed factory.
And also makes not possible to reuse one tag definition.

So my vote is to add `.props()` for tags and computeds. It also would make state usage consistent: `state.set(someTagWithProps.props({}), value)` or `state.get(computedWithProps.props({}))`.

cc @garth

**Comment by christianalfoni** [comment]
So I am the negative one on this ;-) Just adding my comment:

Hm, would ay:

```js
state`foo.${props`bar`}`.props({bar: 'bar'})
```

Is pretty weird :)

Because props is currently "component props", but now they become "default components props, but possibly overided by manual props passing". 

I think :

```js
import {foo} from 'paths/factories'
import {bar} from 'paths/tags'

{
  foo: foo('bar'),
  bar
}
```

Looks more natural.

People might even start to do:

```js
state`foo.${props`bar`}`.props({bar: state`blah`})
```

For some strange reason... I see that it makes things easier, but it adds complexity to the API. But, I would suggest fire up an issue on it and we just discuss with the rest?

We are like "the factory framework" I think, everything can be combined with a factory. Chains, actions, connect, computed... better to teach people good generic JavaScript concepts for abstracting code. Rather than implementing special APIs that can be solved by factories :smiley: anyways, seems like we need more input to conclude on this one :smile:

**Comment by Guria** [comment]
closed as overengineering
