### ISSUE TITLE
React v15.5.0 update. PropTypes deprecated.

### ISSUE THREAD

**Issue by dmitweb** [cerebral/cerebral#827]
"Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead." Please replace PropTypes from React to https://github.com/reactjs/prop-types.
![2017-04-08_213846](https://cloud.githubusercontent.com/assets/5724174/24831535/f604ad0e-1ca3-11e7-8568-ab7ddfe8764b.png)

**Comment by Guria** [comment]
It's not a problem in fact. This warning wouldn't be emitted with react@16 because [PropTypes only used if it exposed in view lib](https://github.com/cerebral/cerebral/blob/master/packages/cerebral/src/viewFactories/Container.js#L25):

react 15.5 with warning https://www.webpackbin.com/bins/-KhETbJaSuGPCn2lrQGS
react 16.0 no warning https://www.webpackbin.com/bins/-KhETs1zUT1DpTNJFHCi

Though, probably move to `prop-types` still can be a good idea if it works well both for React and Inferno.

**Comment by fmal** [comment]
Inferno does not export nor validate PropTypes afaik so they're only relevant for React. I created a PR that addresses this issue: https://github.com/cerebral/cerebral/pull/828

**Comment by fmal** [comment]
@Guria i guess this issue can be closed now (forgot to reference it in commit)
