### ISSUE TITLE
publish cerebral packages in bower

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral#83]

**Comment by christianalfoni** [comment]
Hm, I am quite opinionated about bower. I think more and more devs are moving away from it. The reason is that transpilers are completely taking over and you need browserify/webpack to handle that stuff. And even the new SystemJS that will be what the new JS native module system uses supports all module formats.

I think it is better to bring devs a step into the future than supporting their time in the past :-)

But again, this is my personal opinion.

**Comment by Guria** [comment]
npm
