### ISSUE TITLE
Typescript declaration `connect()` 

### ISSUE THREAD

**Issue by kongdigital** [cerebral/cerebral#962]
What is the correct way for using `connect` with a class component? The typings for connect only allows for a function.

**Comment by kongdigital** [comment]
For example: 
```
import React from 'react'
import {connect} from 'cerebral/react'
import {state} from 'cerebral/tags'

export default connect({
  title: state`title`
},
  class MyComponent extends React.Component {
    render () {
      return (
        <div>
          <h1>{this.props.title}</h1>
        </div>
      )
    }
  }
)
```
Produces an error in typescript TS2345.

**Comment by Guria** [comment]
Typings now very in early state. We will make sure this case to work.

**Comment by kongdigital** [comment]
Yeah I've noticed quite a few pop up now. It's all good. Great to see you expanding the typescript support. 👍

**Comment by christianalfoni** [comment]
Just closing this, please reopen if stuff still missing :)

**Comment by gaspard** [comment]
@kongdigital, type for `connect` should be correct in current master branch. The release is way out of date on types.

I even made a fix and PR to @types/react to support `null` return values in purely functional components because they did not support our types properly with `strictNullChecks`. Needed typescript 2.3 so the fix took some time to land in.

Anyway, this is what we have in master:

```ts
export function connect(propsMap: any, component: React.ComponentClass<any> | React.SFC<any>): React.ComponentClass<any>
export function connect(
  propsMap: any,
  overrideProps: (dependencyProps: any, ownProps: any, resolve: Resolve) => any,
  component: React.ComponentClass<any> | React.SFC<any>
): React.ComponentClass<any>
```
